### PR TITLE
Updated Simslib with Sims 1 chunks compatibility

### PR DESCRIPTION
**Pull request by francot514**
Some sims 1 chunks added to be completed

### CODE REVIEW

**Comment by RHY3756547** [comment]
You seem to have reverted SimsLib's "Iff" to the old format (which is a literal super mess). I also already said that SimsLib is outdated, so you should probably add these to FSO.Files instead (more up to date in every way).

**Comment by francot514** [comment]
Youre not considering that sims 1 uses old format compatibility, and FSO.Files is targeted to TSO so is not really best idea

**Comment by RHY3756547** [comment]
FSO.Files and FSO.SimAntics will eventually be cross compatible. SimsLib is only in the codebase because those tools have not been moved off of it. FSO.Files is the evolution of SimsLib, it doesn't make sense to be going backwards.

**Comment by francot514** [comment]
Ok, no problem so "FSO" will be change eventually? to FS1??

**Comment by RHY3756547** [comment]
No, because that wouldn't represent the cross compatability. Probably something like FSX.

**Pull request closed without merging**
