### PR TITLE
Add objects to catalog

### PR DESCRIPTION
**Pull request by francot514**
Load all objects listed in the file into the catalog_downloads.xml to the uicatalog.

### CODE REVIEW

**Comment by RHY3756547** [comment]
Why did you close this?

**Comment by francot514** [comment]
Because repo is 3 commits behind yours, need to recreate or do you manually

**Comment by RHY3756547** [comment]
There wasn't a merge conflict, I havent touched UICatalog.

Anyways, there is another place we are loading the catalog in content (actually lises by the game instead of just the UI), you should probably do the same thing there.

**Comment by francot514** [comment]
Do you mean class WorldObjectCatalog?

**Comment by RHY3756547** [comment]
Yes.

**Comment by francot514** [comment]
Want me do it again, but using WordObjectCatalog instead of Game UI?

**Comment by RHY3756547** [comment]
You should do it in both, though I'll probably change the game UI to use the WorldObjectCatalog as well to keep things centralised.

**Comment by francot514** [comment]
Ok will do it and push. Please commit before other udpate

**Pull request closed without merging**
